[package]
name = "slice-codec"
description = """
Library for encoding and decoding Slice types.
"""
homepage = "https://docs.icerpc.dev/slice"
documentation = "https://docs.rs/slice-codec"
repository = "https://github.com/icerpc/slicec/slice-codec"
readme = "README.md"
keywords = ["slice", "ice", "icerpc"]
rust-version = "1.74"

# Get these crate fields from the top-level workspace 'Cargo.toml'.
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[lib]
name = "slice_codec"
path = "src/lib.rs"

[dev-dependencies]
test-case = "3.3.1"

[features]
default = ["std", "alloc"]

# Provides implementations for encoding and decoding common standard library types like `String`, `Vec`, `HashMap`, etc.
# Introduces a dependency on the Rust standard library. This flag should be disabled for 'no-std' projects.
std = ["alloc"]

# Provides implementations for decoding common types that require dynamic allocations like `String` and `Vec`.
# This is typically used in no-std environments which have configured their own global allocators.
alloc = []

[package.metadata.docs.rs]
all-features = true
