// Copyright (c) ZeroC, Inc.

//! This module pulls in the parsing code generated by LALRPOP and contains private helper functions used by it.
//!
//! While many of these functions could be written directly into the parser rules, we implement them here instead, to
//! keep the rules focused on grammar instead of implementation details, making the grammar easier to read and modify.

use crate::grammar::{DocComment, Message, MessageComponent};
use crate::slice_file::{Location, Span};
use lalrpop_util::lalrpop_mod;

// Place the code generated by LALRPOP into a submodule named 'lalrpop'.
lalrpop_mod!(
    #[allow(unused, clippy::all)] // LALRPOP generates stuff we don't use, and isn't worth linting.
    pub lalrpop,
    "/parsers/comments/grammar.rs"
);

// Helper macro for storing parsed tags inside the correct field of a doc comment,
// and extending the doc comment's span to the end of the new tag.
macro_rules! append_tag_to_comment {
    ($comment:ident, $field:ident, $block:expr) => {{
        $comment.span.end = $block.span.end;
        $comment.$field.push($block);
        $comment
    }};
}

use append_tag_to_comment; // To let LALRPOP use the macro.

// Grammar Rule Functions

/// Creates a new doc comment with the specified overview and everything else empty.
fn create_doc_comment(overview: Option<Message>, start: Location, file: &str) -> DocComment {
    // We subtract 3 from the start of the comment to account for the leading "///" that is always present.
    // This span is automatically extended as more constructs are parsed.
    let mut span = Span::new(start, start, file);
    span.start.col -= 3;

    // If an overview is present, extend the comment's span to include the overview.
    if let Some(overview_field) = &overview {
        span.end = overview_field.span.end;
    }

    DocComment {
        overview,
        params: Vec::new(),
        returns: Vec::new(),
        see: Vec::new(),
        span,
    }
}

/// Creates a string representing a Slice identifier that can be relatively or globally scoped.
fn get_scoped_identifier_string<'a>(first: &'a str, mut others: Vec<&'a str>, is_globally_scoped: bool) -> String {
    others.insert(0, first);
    if is_globally_scoped {
        others.insert(0, ""); // Gives a leading "::" when we `join`.
    }
    others.join("::")
}

/// Removes any leading whitespace from the inline part of the message, then combines it with any following lines.
fn construct_section_message(
    inline_message: Option<Vec<MessageComponent>>,
    message_lines: Option<Message>,
    span: Span,
) -> Message {
    let mut value = message_lines.map(|m| m.value).unwrap_or_default();

    if let Some(mut message) = inline_message.filter(|m| !m.is_empty()) {
        // Remove any leading whitespace from the inline portion of the message.
        if let Some(MessageComponent::Text(text)) = message.first_mut() {
            *text = text.trim_start().to_owned();
        }

        // Add a newline to the end of the inline message.
        message.push(MessageComponent::Text("\n".to_owned()));

        // Combine the 2 messages together, with the inline portion at the front.
        message.append(&mut value);
        value = message;
    }

    Message { value, span }
}

/// Removes any common leading whitespace from the provided lines and returns the result.
/// Each element in the outermost vector represents one line of the message. These lines may be empty.
///
/// Note that the message's span is not updated to reflect the stripping of common leading whitespace.
fn sanitize_message_lines(lines: Vec<Vec<MessageComponent>>, span: Span) -> Message {
    // Determine the amount of leading whitespace that is common to every line.
    let mut common_leading_whitespace = None;
    for line in &lines {
        // If this line is empty, we don't consider it when determining the common leading whitespace. Just skip it.
        let Some(first_component) = line.first() else { continue };

        // Leading whitespace will always show up as a `Text` component. If the first component is not `Text`,
        // then this line has no leading whitespace, so the _common_ leading whitespace must be empty.
        let MessageComponent::Text(text) = first_component else {
            common_leading_whitespace = Some("");
            break;
        };

        match common_leading_whitespace {
            Some(clw) => {
                let mut comparator_iter = text.char_indices().zip(clw.char_indices());
                let index_of_first_difference = comparator_iter.find_map(|((i, c1), (_, c2))| (c1 != c2).then_some(i));
                let new_prefix_offset = index_of_first_difference.unwrap_or_else(|| text.len().min(clw.len()));
                common_leading_whitespace = Some(&clw[..new_prefix_offset]);
            }
            None => {
                let first_non_whitespace_index = text.find(|c: char| !c.is_whitespace()).unwrap_or(text.len());
                common_leading_whitespace = Some(&text[..first_non_whitespace_index]);
            }
        }
    }
    // All we need is the length of the common leading whitespace.
    let common_leading_whitespace_len = common_leading_whitespace.map_or(0, |clw| clw.len());

    // Remove the common leading whitespace from each line, and we add '\n' to the end of each line for downstream use.
    let sanitized_lines = lines.into_iter().flat_map(|mut line| {
        if let Some(MessageComponent::Text(text)) = line.first_mut() {
            text.drain(..common_leading_whitespace_len);
        }
        line.push(MessageComponent::Text("\n".to_owned()));
        line
    });
    Message {
        value: sanitized_lines.collect(),
        span,
    }
}
