name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        features:
          [
            "",
            "alloc",
            "std",
            "tokio",
            "std,tokio",
            "slice2",
            "slice2,alloc",
            "slice2,std",
            "slice2,tokio",
            "slice2,std,tokio",
          ]
    steps:
      - name: 📦 Setup
        run: echo "FEATURES=${{ matrix.features && '--features ' || '' }}${{ matrix.features }}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: 📦 Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            Cargo.lock
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: 📦 Install
        run: |
          rustup toolchain install nightly
          rustup component add clippy
          rustup component add miri --toolchain nightly
      - name: 🔨 Build
        run: cargo build --no-default-features $FEATURES
      - name: 🧪 Test
        run: cargo +nightly miri test --no-default-features $FEATURES
      - name: 📚 Docs
        run: cargo doc --no-deps --no-default-features --document-private-items $FEATURES
      - name: 🔎 Lint
        run: cargo clippy --all-targets --no-default-features $FEATURES --no-deps

  format:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - name: 📦 Install nightly toolchain
        run: |
          rustup toolchain install nightly
          rustup component add rustfmt --toolchain nightly
      - name: 🔎 Format using rustfmt
        run: cargo +nightly fmt --check
