name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  WARNINGS_AS_ERRORS: yes
  CARGO_TERM_COLOR: always

jobs:
  slicec:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: 📐 Setup
        run: rustup component add clippy
      - name: 📂 Checkout Repository
        uses: actions/checkout@v4
      - name: 🔨 Build
        run: cargo build --all-targets -p slicec
      - name: 🧪 Test
        run: cargo test -p slicec
      - name: 🔎 Lint
        run: cargo clippy --all-targets --no-deps -p slicec
      - name: 📚 Generate Documentation
        run: cargo doc --document-private-items --no-deps -p slicec
        env:
          RUSTDOCFLAGS: "-D warnings"

  slice-codec:
    strategy:
      fail-fast: false
      matrix:
        features: [
          "",
          "alloc",
          "std",
          "tokio",
          "slice2",
          "slice2,alloc",
          "slice2,std",
          "slice2,tokio",
        ]
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: 📐 Setup
        run: |
          echo "FEATURES=${{ matrix.features && '--features ' || '' }}${{ matrix.features }}" >> $GITHUB_ENV
          rustup toolchain install nightly
          rustup component add clippy
          rustup component add miri --toolchain nightly
      - name: 📂 Checkout Repository
        uses: actions/checkout@v4
      - name: 🔨 Build
        run: cargo build --all-targets --no-default-features $FEATURES -p slice-codec
      - name: 🧪 Test
        run: cargo test --no-default-features $FEATURES -p slice-codec
      - name: 📋 Check Soundness
        run: CARGO_TARGET_DIR=miri-target cargo +nightly miri test --no-default-features $FEATURES -p slice-codec
      - name: 🔎 Lint
        run: cargo clippy --all-targets --no-default-features $FEATURES --no-deps -p slice-codec
      - name: 📚 Generate Documentation
        run: cargo doc --document-private-items --no-deps --no-default-features $FEATURES -p slice-codec
        env:
          RUSTDOCFLAGS: "-D warnings"

  format:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: 📂 Checkout Repository
        uses: actions/checkout@v4
      - name: 📐 Setup
        run: |
          rustup toolchain install nightly
          rustup component add rustfmt --toolchain nightly
      - name: 🔎 Check Formatting
        run: cargo +nightly fmt --check
